<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container22VSTQv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container22VSTQv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container22VSTQv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container22VSTQv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container22VSTQv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '22VSTQv',
    'container.build_id' => '2842dd39',
    'container.build_time' => 1583422679,
], __DIR__.\DIRECTORY_SEPARATOR.'Container22VSTQv');
