<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZsfJAzI' shared service.

return $this->privates['.service_locator.ZsfJAzI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'posts' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService.php', true],
    'tags' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService.php', true],
], [
    'posts' => 'App\\Repository\\PostRepository',
    'tags' => 'App\\Repository\\TagRepository',
]);
