<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FS6C2sJ' shared service.

return $this->privates['.service_locator.FS6C2sJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\Admin\\BlogController::delete' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\Admin\\BlogController::edit' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\Admin\\BlogController::index' => ['privates', '.service_locator.1TUE3u0', 'get_ServiceLocator_1TUE3u0Service.php', true],
    'App\\Controller\\Admin\\BlogController::show' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\BlogController::commentForm' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\BlogController::commentNew' => ['privates', '.service_locator.aStR27O', 'get_ServiceLocator_AStR27OService.php', true],
    'App\\Controller\\BlogController::index' => ['privates', '.service_locator.ZsfJAzI', 'get_ServiceLocator_ZsfJAzIService.php', true],
    'App\\Controller\\BlogController::postShow' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\BlogController::search' => ['privates', '.service_locator.1TUE3u0', 'get_ServiceLocator_1TUE3u0Service.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rTcMnXu', 'get_ServiceLocator_RTcMnXuService.php', true],
    'App\\Controller\\UserController::changePassword' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
    'App\\Controller\\Admin\\BlogController:delete' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\Admin\\BlogController:edit' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\Admin\\BlogController:index' => ['privates', '.service_locator.1TUE3u0', 'get_ServiceLocator_1TUE3u0Service.php', true],
    'App\\Controller\\Admin\\BlogController:show' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\BlogController:commentForm' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\BlogController:commentNew' => ['privates', '.service_locator.aStR27O', 'get_ServiceLocator_AStR27OService.php', true],
    'App\\Controller\\BlogController:index' => ['privates', '.service_locator.ZsfJAzI', 'get_ServiceLocator_ZsfJAzIService.php', true],
    'App\\Controller\\BlogController:postShow' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\BlogController:search' => ['privates', '.service_locator.1TUE3u0', 'get_ServiceLocator_1TUE3u0Service.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rTcMnXu', 'get_ServiceLocator_RTcMnXuService.php', true],
    'App\\Controller\\UserController:changePassword' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
], [
    'App\\Controller\\Admin\\BlogController::delete' => '?',
    'App\\Controller\\Admin\\BlogController::edit' => '?',
    'App\\Controller\\Admin\\BlogController::index' => '?',
    'App\\Controller\\Admin\\BlogController::show' => '?',
    'App\\Controller\\BlogController::commentForm' => '?',
    'App\\Controller\\BlogController::commentNew' => '?',
    'App\\Controller\\BlogController::index' => '?',
    'App\\Controller\\BlogController::postShow' => '?',
    'App\\Controller\\BlogController::search' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\UserController::changePassword' => '?',
    'App\\Controller\\Admin\\BlogController:delete' => '?',
    'App\\Controller\\Admin\\BlogController:edit' => '?',
    'App\\Controller\\Admin\\BlogController:index' => '?',
    'App\\Controller\\Admin\\BlogController:show' => '?',
    'App\\Controller\\BlogController:commentForm' => '?',
    'App\\Controller\\BlogController:commentNew' => '?',
    'App\\Controller\\BlogController:index' => '?',
    'App\\Controller\\BlogController:postShow' => '?',
    'App\\Controller\\BlogController:search' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\UserController:changePassword' => '?',
]);
