<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rTcMnXu' shared service.

return $this->privates['.service_locator.rTcMnXu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'helper' => ['services', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService.php', true],
    'security' => ['privates', 'security.helper', 'getSecurity_HelperService.php', true],
], [
    'helper' => '?',
    'security' => '?',
]);
