<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.aStR27O' shared service.

return $this->privates['.service_locator.aStR27O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
    'post' => ['privates', '.errored..service_locator.aStR27O.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.aStR27O": it references class "App\\Entity\\Post" but no such service exists.'],
], [
    'eventDispatcher' => '?',
    'post' => 'App\\Entity\\Post',
]);
