<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'html_sanitizer.form.text_type_extension' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/vendor/tgalopin/html-sanitizer-bundle/src/Form/TextTypeExtension.php';

return $this->privates['html_sanitizer.form.text_type_extension'] = new \HtmlSanitizer\Bundle\Form\TextTypeExtension(($this->privates['html_sanitizer.registry'] ?? $this->getHtmlSanitizer_RegistryService()), 'default');
