<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1TUE3u0' shared service.

return $this->privates['.service_locator.1TUE3u0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'posts' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService.php', true],
], [
    'posts' => 'App\\Repository\\PostRepository',
]);
