<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\CarsUpoadDatabaseFromWebAPICommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/CarsUpoadDatabaseFromWebAPICommand.php';

$this->privates['App\\Command\\CarsUpoadDatabaseFromWebAPICommand'] = $instance = new \App\Command\CarsUpoadDatabaseFromWebAPICommand();

$instance->setName('cars:upoadDatabaseFromWebAPI');

return $instance;
