<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\CarsCronCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/CarsCronCommand.php';

$this->privates['App\\Command\\CarsCronCommand'] = $instance = new \App\Command\CarsCronCommand();

$instance->setName('cars:cron');

return $instance;
